# Generated by Django 5.2.17 on 2026-09-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_sessioncancellation_cancellationresolution'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('event', models.CharField(choices=[('confirmation', 'Confirmation'), ('changed', 'Changed'), ('cancelled', 'Cancelled'), ('reminder', 'Reminder')], max_length=16)),
                ('channel', models.CharField(default='sms', max_length=12)),
                ('destination', models.CharField(max_length=32)),
                ('masked_destination', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='queued', max_length=12)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('provider_reference', models.CharField(blank=True, max_length=64)),
                ('failure_owner', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='appointments.appointment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'status'], name='communicati_facilit_0df58f_idx'), models.Index(fields=['appointment', 'event'], name='communicati_appoint_904df6_idx')],
            },
        ),
    ]
