# Generated by Django 5.2.17 on 2026-09-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
