# Generated by Django 5.2.17 on 2026-09-11 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.schedulerule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.service')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_slot', to='appointments.reservation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='scheduling.session')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['doctor', 'starts_at', 'ends_at'], name='scheduling__doctor__c62928_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('rule', 'date'), name='unique_rule_session_date'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('session', 'starts_at', 'position'), name='unique_session_position'),
        ),
    ]
