# Generated by Django 5.2.17 on 2026-09-11 10:46

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='Asia/Colombo', max_length=64)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('accepts_registration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.CharField(default='Unavailable', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.organization'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_until', models.DateField(blank=True, help_text='Exclusive end date; blank means no end.', null=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_until', models.DateField(blank=True, help_text='Exclusive end date; blank means no end.', null=True)),
                ('doctor_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('facility_fee', models.DecimalField(decimal_places=2, default=500, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='configuration.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.specialty'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('booking_confirmed', 'Booking confirmation'), ('appointment_changed', 'Appointment change'), ('appointment_cancelled', 'Cancellation'), ('reminder', 'Reminder')], max_length=40)),
                ('language', models.CharField(default='en', max_length=8)),
                ('body', models.TextField(help_text='Use {reference}, {date}, {time}, {facility}. No clinical information.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'event', 'language'), name='unique_message_template')],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_until', models.DateField(blank=True, help_text='Exclusive end date; blank means no end.', null=True)),
                ('version', models.CharField(max_length=32)),
                ('hold_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('cancellation_hours', models.PositiveSmallIntegerField(default=24)),
                ('release_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'version'), name='unique_policy_version')],
            },
        ),
    ]
