# Generated by Django 5.2.17 on 2026-09-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='dead_lettered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='failure_owner',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='last_error',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
