# Generated by Django 5.2.17 on 2026-09-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentchange',
            new_name='finance_app_origina_98d521_idx',
            old_name='finance_app_original_3d7f5f_idx',
        ),
        migrations.RenameIndex(
            model_name='checkout',
            new_name='finance_che_status_47afcf_idx',
            old_name='finance_chec_status_0a6c66_idx',
        ),
        migrations.RenameIndex(
            model_name='financeexception',
            new_name='finance_fin_facilit_1682dd_idx',
            old_name='finance_fin_facility_8a6e03_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='finance_pay_appoint_706fc3_idx',
            old_name='finance_pay_appointm_8f3d3f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='finance_pay_facilit_f4bfec_idx',
            old_name='finance_pay_facility_9a2f6a_idx',
        ),
    ]
