# Generated by Django 5.2.17 on 2026-09-11 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_sessioncancellation_cancellationresolution'),
        ('configuration', '0001_initial'),
        ('finance', '0002_rename_finance_app_original_3d7f5f_idx_finance_app_origina_98d521_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('versioned', 'Versioned'), ('paid', 'Paid'), ('void', 'Void')], default='versioned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_payable', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='configuration.doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('source_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_payables', to='finance.payment')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('transaction_reference', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status_value', models.CharField(blank=True, max_length=32)),
                ('provider_event_id', models.CharField(blank=True, max_length=128)),
                ('row_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('amount_mismatch', 'Amount mismatch'), ('invalid', 'Invalid')], max_length=20)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='finance.gatewayimport')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_rows', to='finance.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.settlementbatch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.doctor')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='finance.doctorpayable')),
            ],
        ),
        migrations.AddIndex(
            model_name='doctorpayable',
            index=models.Index(fields=['facility', 'doctor', 'status'], name='finance_doc_facilit_c86206_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatewayimport',
            constraint=models.UniqueConstraint(fields=('facility', 'file_hash'), name='finance_gateway_file_once'),
        ),
        migrations.AddConstraint(
            model_name='gatewayimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='finance_gateway_row_once'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatch',
            constraint=models.UniqueConstraint(fields=('facility', 'reference'), name='finance_settlement_reference_once'),
        ),
    ]
