# Generated by Django 5.2.17 on 2026-09-12 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preflight(apps, schema_editor):
    Line = apps.get_model('finance', 'SettlementLine')
    Batch = apps.get_model('finance', 'SettlementBatch')
    seen, conflicts = set(), []
    for line in Line.objects.using(schema_editor.connection.alias).order_by('pk'):
        if not line.payable_id or line.amount < 0 or line.adjustment != 0 or line.payable_id in seen:
            conflicts.append(line.pk)
        seen.add(line.payable_id)
    adjusted = list(Batch.objects.using(schema_editor.connection.alias).exclude(adjustment=0).values_list('pk', flat=True))
    if conflicts or adjusted:
        raise RuntimeError(
            f'Financial migration requires reconciliation. Conflicting/unlinked settlement line IDs: {conflicts}; '
            f'unbacked batch adjustment IDs: {adjusted}. Preserve all records; establish original allocation and '
            'supporting refund links with finance approval before retrying. No records have been deleted.')


def backfill(apps, schema_editor):
    alias = schema_editor.connection.alias
    Line = apps.get_model('finance', 'SettlementLine')
    for line in Line.objects.using(alias).all():
        Line.objects.using(alias).filter(pk=line.pk).update(original_payable_id=line.payable_id)
    # Old pending rows have no proven external operation identity. Never resubmit them automatically.
    apps.get_model('finance', 'RefundObligation').objects.using(alias).filter(status='pending').update(
        status='unknown', failure_owner='finance', last_error='Legacy refund requires provider reconciliation.')


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('finance', '0003_doctorpayable_gatewayimport_gatewayimportrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.AddField(
            model_name='refundobligation',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='failure_owner',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='last_error',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='method',
            field=models.CharField(default='counter', max_length=12),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='refundobligation',
            name='source_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_operations', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='kind',
            field=models.CharField(choices=[('original', 'Original'), ('refund', 'Refund adjustment')], default='original', max_length=12),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='original_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_adjustments', to='finance.settlementline'),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='original_payable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_allocation', to='finance.doctorpayable'),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_adjustment', to='finance.payment'),
        ),
        migrations.AlterField(
            model_name='refundobligation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitting', 'Submitting'), ('unknown', 'Unknown'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment', 0), ('amount__gte', 0), ('kind', 'original'), ('original_line__isnull', True), ('original_payable__isnull', False), ('payable', models.F('original_payable')), ('refund__isnull', True)), models.Q(('adjustment', 0), ('amount__lt', 0), ('kind', 'refund'), ('original_line__isnull', False), ('original_payable__isnull', True), ('payable__isnull', False), ('refund__isnull', False)), _connector='OR'), name='settlement_line_shape'),
        ),
    ]
