# Generated by Django 5.2.17 on 2026-09-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preflight(apps, schema_editor):
    Payment = apps.get_model('finance', 'Payment')
    for field in ['obligation_id', 'checkout_id']:
        duplicate_ids = list(Payment.objects.using(schema_editor.connection.alias)
            .exclude(**{field: None}).values(field).annotate(count=models.Count('pk'))
            .filter(count__gt=1).values_list(field, flat=True))
        if duplicate_ids:
            raise RuntimeError(f'Duplicate payment ledger relationships for {field}: {duplicate_ids}. '
                               'Reconcile existing payments before applying uniqueness; no records were deleted.')


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_sessioncancellation_cancellationresolution'),
        ('configuration', '0001_initial'),
        ('finance', '0004_refundobligation_actor_refundobligation_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SettlementMutex',
            fields=[
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='configuration.facility')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('obligation',), name='refund_operation_one_ledger'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('checkout',), name='checkout_one_ledger'),
        ),
    ]
