# Generated by Django 5.2.17 on 2026-09-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.patient'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'facility'), name='unique_membership'),
        ),
    ]
