# Generated by Django 5.2.17 on 2026-09-11 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('state', models.CharField(default='confirmed', max_length=24)),
                ('payment_state', models.CharField(default='counter_due', max_length=24)),
                ('source', models.CharField(max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('reason_category', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.service')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('held', 'Held'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.patient')),
            ],
        ),
    ]
