# Generated by Django 5.2.17 on 2026-09-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='scheduling.slot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'expires_at'], name='appointment_status_b86ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility', 'starts_at', 'state'], name='appointment_facilit_7b3df6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'starts_at'], name='appointment_doctor__60bd67_idx'),
        ),
    ]
