# Generated by Django 5.2.17 on 2026-09-11 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('configuration', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.facility')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='scheduling.session')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='pending', max_length=12)),
                ('outcome', models.CharField(blank=True, choices=[('refund', 'Refund'), ('rescheduled', 'Rescheduled'), ('credit', 'Credit'), ('unreachable', 'Unreachable')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_resolution', to='appointments.appointment')),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='appointments.sessioncancellation')),
            ],
            options={
                'indexes': [models.Index(fields=['cancellation', 'status'], name='appointment_cancell_9e9555_idx')],
            },
        ),
    ]
